name: Playwright Tests

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Start development server
        run: |
          echo "=== Starting development server ==="
          nohup npm run dev > server.log 2>&1 &
          echo $! > server.pid
          echo "Server PID: $(cat server.pid)"
          
          echo "=== Waiting for server to start ==="
          for i in {1..30}; do
            if curl -f http://localhost:8081 >/dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            echo "Attempt $i: Server not ready, waiting..."
            sleep 2
          done
          
          if ! curl -f http://localhost:8081 >/dev/null 2>&1; then
            echo "=== Server failed to start ==="
            echo "Server log:"
            cat server.log
            exit 1
          fi
      
      - name: Run Playwright tests
        run: npm run test:e2e
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            playwright-report/
            server.log
          retention-days: 30