name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test:run

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Start HTTP server in background
      run: |
        echo "Starting server..."
        npm run dev &
        SERVER_PID=$!
        echo "Server PID: $SERVER_PID"
        sleep 10
        echo "Testing server connection..."
        curl -f http://localhost:8081 || (echo "Server failed to start" && exit 1)
        echo "Server is running!"
    
    - name: Run Playwright tests  
      run: npx playwright test --project=chromium --reporter=list --timeout=30000
    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
EOF < /dev/null